const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
async function fixture(){const THREE=await import(pathToFileURL(path.resolve(__dirname,'../vendor/three-r186/build/three.webgpu.js')).href),{createHallGlassPassStudy}=await import('../assets-src/shinsekai/browser-study/hall-glass-pass-study.mjs');return {THREE,createHallGlassPassStudy};}
test('glass study owns shared copies, preserves source alpha/maps/geometry and restores without disposing sources',async()=>{
 const {THREE,createHallGlassPassStudy}=await fixture(),scene=new THREE.Scene(),map=new THREE.Texture(),material=new THREE.MeshStandardMaterial({transparent:true,opacity:.12,side:THREE.DoubleSide,map}),geometry=new THREE.BoxGeometry(),meshes=['TB_EXT_LOD0_glass','TW_LOD0_glass','hall__windows_doors_4','other'].map(name=>{const m=new THREE.Mesh(geometry,material);m.name=name;scene.add(m);return m;});let sourceDisposed=0,copyDisposed=0;material.addEventListener('dispose',()=>sourceDisposed++);geometry.addEventListener('dispose',()=>sourceDisposed++);map.addEventListener('dispose',()=>sourceDisposed++);
 const scope=createHallGlassPassStudy(scene,{mode:'exteriorcontrol'}),copy=meshes[0].material;copy.addEventListener('dispose',()=>copyDisposed++);
 assert.notEqual(copy,material);assert.equal(copy,meshes[1].material);assert.equal(meshes[2].material,material);assert.equal(meshes[3].material,material);assert.equal(copy.map,map);assert.equal(copy.opacity,material.opacity);assert.equal(copy.forceSinglePass,false);assert.equal(copy.side,material.side);assert.ok(meshes.every(m=>m.geometry===geometry));assert.equal(scope.stats.ownedMaterials,1);
 assert.equal(scope.dispose().sourceAssignmentsRestored,true);assert.equal(scope.dispose(),null);assert.ok(meshes.every(m=>m.material===material));assert.equal(copyDisposed,1);assert.equal(sourceDisposed,0);
 const single=createHallGlassPassStudy(scene,{mode:'singlepass'});assert.equal(meshes[0].material.forceSinglePass,true);assert.equal(material.forceSinglePass,false);single.dispose();assert.equal(sourceDisposed,0);
});
test('failed glass qualification rolls back already assigned copies and disposes only owned candidates',async()=>{
 const {THREE,createHallGlassPassStudy}=await fixture(),scene=new THREE.Scene(),good=new THREE.MeshStandardMaterial({transparent:true,side:THREE.DoubleSide}),bad=new THREE.MeshStandardMaterial(),a=new THREE.Mesh(new THREE.BoxGeometry(),good),b=new THREE.Mesh(new THREE.BoxGeometry(),bad);a.name='TB_EXT_LOD0_glass';b.name='TW_LOD0_glass';scene.add(a,b);let sourceDisposed=0;good.addEventListener('dispose',()=>sourceDisposed++);assert.throws(()=>createHallGlassPassStudy(scene),/Expected/);assert.equal(a.material,good);assert.equal(b.material,bad);assert.equal(sourceDisposed,0);
});
