const test=require('node:test'),assert=require('node:assert/strict');
async function fixture(){return {createHallFloorContactLook:(await import('../assets-src/shinsekai/browser-study/hall-floor-contact-look.mjs')).createHallFloorContactLook,createHallFloorLook:(await import('../assets-src/shinsekai/browser-study/hall-floor-look.mjs')).createHallFloorLook};}
test('baked floor scope owns only its additional map and preserves original maps/geometry/assignments through copy and retirement',async()=>{
 const {createHallFloorContactLook,createHallFloorLook}=await fixture();let mapDisposed=0,copiesDisposed=0;const map={isTexture:true,image:{width:512,height:2048},colorSpace:'',flipY:true,dispose(){mapDisposed++;}},sourceMap={},normalMap={},floor={name:'stone_floor',roughness:.1,map:sourceMap,normalMap},worn={name:'stone_floor_worn',roughness:.34,map:sourceMap},wall={},original=[floor,worn,wall],geometry={},mesh={isMesh:true,material:original,geometry},model={scene:{traverse(fn){fn(mesh);}}};
 const contact=createHallFloorContactLook(map,{gain:.8,buildNode:(original,map,gain)=>({original,map,gain})});
 const look=createHallFloorLook(model,{mode:'wear',createMaterial:s=>({...s,dispose(){copiesDisposed++;}}),decorateWear:m=>{m.colorNode={wear:true};contact.decorate(m);}});
 assert.equal(mesh.material[0].colorNode.map,map);assert.equal(mesh.material[0].colorNode.original.wear,true);assert.equal(mesh.material[0].colorNode.gain,.8);assert.equal(mesh.material[0].map,sourceMap);assert.equal(mesh.material[0].normalMap,normalMap);assert.equal(mesh.material[2],wall);assert.equal(mesh.geometry,geometry);assert.equal(floor.colorNode,undefined);assert.equal(contact.stats.materials,2);assert.equal(contact.stats.ownedTextureObjects,1);assert.throws(()=>contact.decorate(mesh.material[0]),/Invalid/);
 look.dispose();assert.equal(mesh.material,original);assert.equal(copiesDisposed,2);assert.equal(mapDisposed,0);assert.equal(contact.dispose().ownedTexturesDisposed,1);assert.equal(contact.dispose(),null);assert.equal(mapDisposed,1);assert.throws(()=>contact.decorate({name:'stone_floor'}),/Invalid/);
});
test('invalid baked map fails before material changes; failed decorator restores source and null gain retains exact supplied colour factor',async()=>{
 const {createHallFloorContactLook,createHallFloorLook}=await fixture();let disposed=0;const map={isTexture:true,image:{width:512,height:2048},colorSpace:'',flipY:true,dispose(){disposed++;}},node={},floor={name:'stone_floor',roughness:.1},worn={name:'stone_floor_worn',roughness:.34},original=[floor,worn],mesh={isMesh:true,material:original},model={scene:{traverse(fn){fn(mesh);}}};
 for(const invalid of [{...map,colorSpace:'srgb'},{...map,flipY:false},{...map,image:{width:512,height:512}}])assert.throws(()=>createHallFloorContactLook(invalid,{buildNode(){}}),/Invalid/);
 assert.throws(()=>createHallFloorContactLook(map,{gain:-1,buildNode(){}}),/Invalid/);assert.equal(disposed,0);
 const control=createHallFloorContactLook(map,{gain:0,buildNode:(original,map,gain)=>{assert.equal(gain,0);return original;}}),copy={name:'stone_floor',colorNode:node};control.decorate(copy);assert.equal(copy.colorNode,node);control.dispose();
 const map2={...map},failed=createHallFloorContactLook(map2,{buildNode(){throw Error('node failure');}});let cleaned=0;assert.throws(()=>createHallFloorLook(model,{mode:'wear',createMaterial:s=>({...s,dispose(){cleaned++;}}),decorateWear:m=>failed.decorate(m)}),/node failure/);assert.equal(mesh.material,original);assert.equal(cleaned,1);assert.equal(floor.colorNode,undefined);failed.dispose();assert.equal(disposed,2);
});
