const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
async function fixture(){const THREE=await import(pathToFileURL(path.resolve(__dirname,'../vendor/three-r186/build/three.webgpu.js')).href),{createHallFillLook}=await import('../assets-src/shinsekai/browser-study/hall-fill-look.mjs');return {THREE,createHallFillLook};}
test('hall fill preserves original light identity/RGB/target/shadow and restores current source intensity on success/throw without compounding',async()=>{
 const {THREE,createHallFillLook}=await fixture(),light=new THREE.DirectionalLight(0xffe2ba,3),scene=new THREE.Scene(),hemi=new THREE.HemisphereLight(0xdce7f1,0x72614e,1.2);scene.add(light,hemi);light.position.set(-20,40,30);const shadow=light.shadow,target=light.target,rgb=light.color.toArray(),position=light.position.toArray(),children=scene.children.slice();let disposed=0;light.addEventListener('dispose',()=>disposed++);
 const scope=createHallFillLook(light,{gain:.1}),check=()=>{assert.equal(light.intensity,3*.1);assert.equal(light.shadow,shadow);assert.equal(light.target,target);assert.deepEqual(light.color.toArray(),rgb);assert.deepEqual(light.position.toArray(),position);assert.equal(light.castShadow,false);assert.equal(hemi.intensity,1.2);assert.deepEqual(scene.children,children);};
 assert.equal(scope.withApplied(()=>{check();return 42;}),42);assert.equal(light.intensity,3);assert.throws(()=>scope.withApplied(()=>{check();throw Error('draw failure');}),/draw failure/);assert.equal(light.intensity,3);assert.equal(scope.stats.last.sourceRestored,true);
 light.intensity=2;scope.withApplied(()=>assert.equal(light.intensity,.2));assert.equal(light.intensity,2);assert.throws(()=>scope.withApplied(()=>scope.withApplied(()=>{})),/Invalid/);assert.equal(light.intensity,2);assert.throws(()=>scope.withApplied(()=>scope.dispose()),/active/);assert.equal(light.intensity,2);assert.equal(scope.dispose().ownedResources,0);assert.equal(scope.dispose(),null);assert.throws(()=>scope.withApplied(()=>{}),/Invalid/);assert.equal(disposed,0);
});
test('fill no-op/zero and invalid setup preserve source and reject a mutated invalid scalar before rendering',async()=>{
 const {THREE,createHallFillLook}=await fixture(),light=new THREE.DirectionalLight(0xffffff,3);
 for(const gain of [1,0,.25,.5]){const scope=createHallFillLook(light,{gain});scope.withApplied(()=>assert.equal(light.intensity,3*gain));assert.equal(light.intensity,3);scope.dispose();}
 for(const gain of [-1,.2,NaN,Infinity])assert.throws(()=>createHallFillLook(light,{gain}),/Invalid/);assert.equal(light.intensity,3);assert.throws(()=>createHallFillLook(new THREE.PointLight()),/Invalid/);const scope=createHallFillLook(light);light.intensity=NaN;let called=false;assert.throws(()=>scope.withApplied(()=>called=true),/Invalid/);assert.equal(called,false);assert.ok(Number.isNaN(light.intensity));scope.dispose();
});
test('async preparation holds the rendering intensity through completion and rejection, with exclusive ownership and restoration',async()=>{
 const {THREE,createHallFillLook}=await fixture(),light=new THREE.DirectionalLight(0xffffff,3),scope=createHallFillLook(light,{gain:.25});let finish;
 const gate=new Promise(resolve=>finish=resolve),pending=scope.withAppliedAsync(async()=>{assert.equal(light.intensity,.75);await gate;assert.equal(light.intensity,.75);return 42;});
 assert.equal(light.intensity,.75);assert.throws(()=>scope.withApplied(()=>{}),/Invalid/);assert.throws(()=>scope.dispose(),/active/);await assert.rejects(scope.withAppliedAsync(()=>{}),/Invalid/);finish();assert.equal(await pending,42);assert.equal(light.intensity,3);assert.equal(scope.stats.last.sourceRestored,true);
 await assert.rejects(scope.withAppliedAsync(async()=>{await Promise.resolve();assert.equal(light.intensity,.75);throw Error('compile failed');}),/compile failed/);assert.equal(light.intensity,3);scope.dispose();await assert.rejects(scope.withAppliedAsync(()=>{}),/Invalid/);
});
