/* Editorial comparison prompts, not inferred visitor preferences or historical dates. */
const langs=['en','ja','ko','zh-Hans','zh-Hant','th'];
const rows={
hiroshima:['Trace the Motoyasu River beside the Atomic Bomb Dome, then compare the surrounding blocks with Peace Memorial Park. The dome is one of the surviving atomic-bombed structures, not the only building that remained.','原爆ドームに沿う元安川を目印に、周辺の街区と平和記念公園を比較します。原爆ドームは被爆して残った建物の一つで、唯一残った建物ではありません。','원폭 돔 옆 모토야스강을 기준으로 주변 시가지와 평화기념공원을 비교해 보세요. 원폭 돔은 남아 있는 피폭 건축물 중 하나이며 유일하게 남은 건물은 아닙니다.','以原爆圆顶馆旁的元安川为参照，对比周围街区与和平纪念公园。原爆圆顶馆是幸存的被爆建筑之一，并非唯一留下的建筑。','以原爆圓頂館旁的元安川為參照，比較周圍街區與和平紀念公園。原爆圓頂館是留存的被爆建築之一，並非唯一留下的建築。','ใช้แม่น้ำโมโตยาสุข้างโดมปรมาณูเป็นจุดอ้างอิง แล้วเปรียบเทียบย่านโดยรอบกับสวนสันติภาพ โดมเป็นหนึ่งในอาคารที่หลงเหลือจากเหตุระเบิดปรมาณู ไม่ใช่อาคารเพียงแห่งเดียวที่เหลืออยู่'],
tokyo:['Find Senso-ji and follow the approach towards the Sumida River. Compare the temple grounds, nearby shopping streets and the density of surrounding buildings.','浅草寺を見つけ、参道から隅田川の方向へたどります。境内、周辺の商店街、建物の密集のしかたを見比べてください。','센소지를 찾고 참배길에서 스미다강 방향으로 살펴보세요. 경내와 주변 상점가, 건물의 밀집 정도를 비교해 보세요.','找到浅草寺，沿参道向隅田川方向探索。比较寺院用地、周围商店街和建筑的密集程度。','找到淺草寺，沿參道向隅田川方向探索。比較寺院用地、周圍商店街與建築的密集程度。','เริ่มจากวัดเซ็นโซจิ แล้วมองตามทางเดินไปยังแม่น้ำสุมิดะ เปรียบเทียบพื้นที่วัด ถนนร้านค้า และความหนาแน่นของอาคารโดยรอบ'],
kyoto:['Use Kiyomizu-dera as an anchor between the wooded hillside and the streets of Higashiyama. Look for the boundary between temple grounds, trees and the built-up city.','清水寺を目印に、木々に覆われた斜面と東山の街路を見比べます。寺域、森林、市街地の境界に注目してください。','기요미즈데라를 기준으로 숲이 있는 비탈과 히가시야마의 거리를 비교해 보세요. 사찰과 숲, 시가지의 경계를 찾아보세요.','以清水寺为中心，对比林木覆盖的山坡与东山街道。留意寺院、树林和市区之间的边界。','以清水寺為中心，比較林木覆蓋的山坡與東山街道。留意寺院、樹林與市區之間的邊界。','ใช้วัดคิโยมิซุเป็นจุดอ้างอิงระหว่างเนินเขาที่มีต้นไม้กับถนนในฮิกาชิยามะ สังเกตขอบเขตระหว่างวัด ป่า และย่านเมือง'],
yokohama:['Follow the waterfront around Minato Mirai. Compare the outlines of docks, reclaimed land and present-day parks; the coastline is as useful a clue as the buildings.','みなとみらいの水際をたどり、ドック、埋立地、現在の公園の形を見比べます。建物だけでなく海岸線も変化を読む手掛かりです。','미나토미라이의 해안을 따라 부두, 매립지, 현재 공원의 윤곽을 비교해 보세요. 건물뿐 아니라 해안선도 변화의 단서입니다.','沿港未来的水岸比较船坞、填海地与今日公园的轮廓。海岸线和建筑一样，也是观察变化的线索。','沿港未來的水岸比較船塢、填海地與今日公園的輪廓。海岸線和建築一樣，也是觀察變化的線索。','มองตามแนวริมน้ำของมินาโตมิไร เปรียบเทียบอู่เรือ พื้นที่ถมทะเล และสวนในปัจจุบัน แนวชายฝั่งช่วยให้เห็นการเปลี่ยนแปลงได้เช่นเดียวกับอาคาร'],
osaka:['Start with Osaka Castle and its moats. Compare the land outside the walls with the park and railway corridors visible on the current map.','大阪城と堀を起点に、城壁の外側にある土地を見ます。現在の公園や鉄道沿いの空間と比べてみてください。','오사카성과 해자에서 시작해 성벽 바깥의 땅을 살펴보세요. 현재 지도에 보이는 공원과 철도 주변 공간을 비교해 보세요.','从大阪城和护城河开始，观察城墙外的土地，与现在的公园和铁路沿线空间进行比较。','從大阪城與護城河開始，觀察城牆外的土地，與現在的公園及鐵路沿線空間比較。','เริ่มจากปราสาทโอซาก้าและคูน้ำ แล้วเปรียบเทียบพื้นที่นอกกำแพงกับสวนและแนวทางรถไฟบนแผนที่ปัจจุบัน'],
kamakura:['Locate the Great Buddha at Kotoku-in, then examine the temple grounds and roads towards Hase. Compare the wooded slopes with the neighbourhood below.','高徳院の大仏を見つけ、境内と長谷へ続く道をたどります。周辺の山林と住宅地の広がりを比較してください。','고토쿠인 대불을 찾고 경내와 하세로 이어지는 길을 살펴보세요. 숲이 있는 비탈과 그 아래 주거지를 비교해 보세요.','找到高德院大佛，查看寺院用地与通往长谷的道路。比较林木覆盖的山坡和下方街区。','找到高德院大佛，查看寺院用地與通往長谷的道路。比較林木覆蓋的山坡和下方街區。','หาพระใหญ่ที่วัดโคโตคุอิน แล้วสำรวจบริเวณวัดกับถนนสู่ฮาเซะ เปรียบเทียบเนินเขาที่มีต้นไม้กับย่านที่อยู่อาศัยด้านล่าง'],
kobe:['Use Meriken Park to explore Kobe’s harbour edge. Follow the piers and waterfront roads, looking for differences in the shape and use of the shoreline.','メリケンパークを起点に神戸港の水際を見ます。突堤と海沿いの道をたどり、岸辺の形や使われ方の変化を探してください。','메리켄 공원에서 고베항의 해안을 살펴보세요. 부두와 해안 도로를 따라 해안의 형태와 용도 변화를 찾아보세요.','从美利坚公园探索神户港。沿码头和滨海道路观察岸线形状与土地用途的变化。','從美利堅公園探索神戶港。沿碼頭和濱海道路觀察岸線形狀與土地用途的變化。','เริ่มที่สวนเมริเคนแล้วสำรวจริมอ่าวโกเบ มองตามท่าเรือและถนนริมน้ำเพื่อเปรียบเทียบรูปร่างและการใช้พื้นที่ชายฝั่ง'],
okayama:['Follow the Asahi River around Okayama Castle. Compare the castle grounds and riverbanks before looking at the streets beyond them.','岡山城に沿う旭川をたどります。城の敷地と川岸を比較し、さらに外側の街路へ視点を広げてみてください。','오카야마성 주변의 아사히강을 따라가 보세요. 성터와 강변을 비교한 뒤 주변 거리로 시야를 넓혀 보세요.','沿冈山城周围的旭川探索。先比较城址和河岸，再观察外围街道。','沿岡山城周圍的旭川探索。先比較城址和河岸，再觀察外圍街道。','มองตามแม่น้ำอาซาฮิรอบปราสาทโอคายามะ เปรียบเทียบบริเวณปราสาทและริมแม่น้ำก่อนขยายไปดูถนนรอบนอก'],
aneyoshi:['Locate the tsunami memorial stone and read the surrounding hillside on the map. This is a place to learn about local disaster memory; this page is not an evacuation map.','津波の教訓を伝える碑を探し、周辺の斜面と集落の位置を地図で確認します。地域の災害の記憶を学ぶページであり、避難経路図ではありません。','쓰나미 교훈을 전하는 비석과 주변 비탈, 마을의 위치를 살펴보세요. 지역의 재해 기억을 배우는 페이지이며 대피 경로 지도는 아닙니다.','找到记录海啸教训的石碑，查看周围山坡与村落的位置。这是了解当地灾害记忆的页面，不是疏散路线图。','找到記錄海嘯教訓的石碑，查看周圍山坡與聚落的位置。這是了解當地災害記憶的頁面，不是疏散路線圖。','ค้นหาศิลาจารึกเตือนสึนามิและดูตำแหน่งหมู่บ้านกับเนินเขารอบ ๆ หน้านี้ใช้เรียนรู้ความทรงจำเกี่ยวกับภัยพิบัติ ไม่ใช่แผนที่เส้นทางอพยพ'],
nagasaki:['Look for Nagasaki Peace Park in the valley. The selected historical layer is from the 1960s, so it shows the city after reconstruction had begun, not the immediate aftermath of 1945.','谷あいにある長崎の平和公園を探します。選択されている歴史写真は1960年代のため、1945年の被爆直後ではなく復興が進んだ時期の街を示しています。','골짜기에 있는 나가사키 평화공원을 찾아보세요. 선택된 옛 사진은 1960년대 자료로 1945년 직후가 아니라 복구가 진행된 시기의 도시를 보여 줍니다.','寻找山谷中的长崎和平公园。所选历史图层来自1960年代，展示的是重建已开始后的城市，而非1945年被爆后不久的景象。','尋找山谷中的長崎和平公園。所選歷史圖層來自1960年代，展示的是重建已開始後的城市，而非1945年被爆後不久的景象。','มองหาสวนสันติภาพนางาซากิในหุบเขา ภาพเก่าที่เลือกมาจากทศวรรษ 1960 จึงแสดงเมืองในช่วงฟื้นฟู ไม่ใช่สภาพทันทีหลังปี 1945'],
sapporo:['Find the grid of streets around central Sapporo. Follow a straight road across several blocks and compare open spaces, parks and the spread of buildings.','札幌中心部の格子状の街路を探します。一本の直線道路を数街区たどり、空地、公園、建物の広がりを比べてみてください。','삿포로 중심부의 격자형 도로를 찾아보세요. 직선 도로를 따라 여러 구역을 살펴보며 빈터와 공원, 건물의 분포를 비교해 보세요.','找到札幌中心的棋盘状街道。沿一条直路观察几个街区，比较空地、公园和建筑的分布。','找到札幌中心的棋盤狀街道。沿一條直路觀察幾個街區，比較空地、公園與建築的分布。','หาถนนตารางในใจกลางซัปโปโร ลองมองตามถนนเส้นตรงผ่านหลายช่วงตึก แล้วเปรียบเทียบพื้นที่ว่าง สวน และการกระจายของอาคาร'],
hakodate:['Compare Hakodate’s harbour with the streets rising towards the mountain. The narrow landform helps you keep your bearings as you change between photo layers.','函館の港と山側へ続く街路を見比べます。細く伸びる地形を目印にすると、写真の年代を切り替えても位置関係を追いやすくなります。','하코다테항과 산으로 이어지는 거리를 비교해 보세요. 좁게 뻗은 지형을 기준으로 삼으면 사진을 바꿔도 위치를 파악하기 쉽습니다.','比较函馆港与通向山坡的街道。以狭长地形为参照，切换照片图层时更容易辨认位置。','比較函館港與通向山坡的街道。以狹長地形為參照，切換照片圖層時更容易辨認位置。','เปรียบเทียบท่าเรือฮาโกดาเตะกับถนนที่ขึ้นไปทางภูเขา รูปร่างแผ่นดินที่แคบช่วยให้จดจำตำแหน่งได้เมื่อเปลี่ยนชั้นภาพ'],
nagoya:['Use the moats of Nagoya Castle to align the two views. Compare the grounds inside them with the roads and city blocks outside.','名古屋城の堀を目印に二つの景色を重ねます。堀の内側の敷地と外側の道路・街区を比較してください。','나고야성의 해자를 기준으로 두 풍경을 맞춰 보세요. 해자 안쪽의 땅과 바깥쪽 도로, 시가지를 비교해 보세요.','以名古屋城的护城河为参照，对齐两幅景象。比较河内的城址与外围道路、街区。','以名古屋城的護城河為參照，對齊兩幅景象。比較河內的城址與外圍道路、街區。','ใช้คูน้ำปราสาทนาโกย่าเป็นจุดอ้างอิง เปรียบเทียบพื้นที่ด้านในกับถนนและย่านเมืองด้านนอก'],
himeji:['Find Himeji Castle and follow the main approach south into the city. Compare the castle grounds, green spaces and the arrangement of streets around them.','姫路城を見つけ、南へ延びる道を市街地に向かってたどります。城の敷地、緑地、周辺の街路配置を比較してください。','히메지성을 찾고 남쪽 시가지로 이어지는 길을 따라가 보세요. 성터와 녹지, 주변 도로 배치를 비교해 보세요.','找到姬路城，沿向南的道路探索市区。比较城址、绿地和周围街道的布局。','找到姬路城，沿向南的道路探索市區。比較城址、綠地與周圍街道的布局。','หาปราสาทฮิเมจิแล้วมองตามถนนลงไปทางใต้สู่ตัวเมือง เปรียบเทียบพื้นที่ปราสาท สวน และรูปแบบถนนรอบ ๆ'],
nara:['Locate Todai-ji and compare its grounds with the open areas of Nara Park. Use the transition from town to wooded hills to orient the photographs.','東大寺を探し、境内と奈良公園の開けた場所を見比べます。市街地から山林へ移る境界を写真の位置合わせに使ってください。','도다이지 경내와 나라공원의 열린 공간을 비교해 보세요. 시가지에서 숲으로 이어지는 경계를 사진의 기준점으로 삼아 보세요.','找到东大寺，将寺院用地与奈良公园的开阔区域比较。以市区向山林过渡的边界辨认照片方位。','找到東大寺，將寺院用地與奈良公園的開闊區域比較。以市區向山林過渡的邊界辨認照片方位。','หาวัดโทไดจิแล้วเปรียบเทียบบริเวณวัดกับพื้นที่เปิดในสวนนารา ใช้รอยต่อระหว่างเมืองกับเนินเขาที่มีต้นไม้ช่วยระบุตำแหน่ง'],
kanazawa:['Compare the castle area and Kenroku-en with the surrounding streets. Look for contrasts between broad grounds, narrow lanes and waterways.','城の周辺と兼六園を、外側の街路と見比べます。広い敷地、細い路地、水路の違いに注目してみてください。','성 주변과 겐로쿠엔을 주위 거리와 비교해 보세요. 넓은 부지, 좁은 골목, 수로의 차이를 살펴보세요.','将城址周边和兼六园与外围街道比较。留意大片用地、狭窄小巷和水道之间的差异。','將城址周邊與兼六園和外圍街道比較。留意大片用地、狹窄小巷與水道之間的差異。','เปรียบเทียบบริเวณปราสาทและสวนเค็นโรคุเอ็นกับถนนรอบ ๆ สังเกตความแตกต่างระหว่างพื้นที่กว้าง ตรอกเล็ก และทางน้ำ'],
sendai:['Look for the tree-lined avenues in central Sendai. Compare the width of streets and the distribution of green space across the city blocks.','仙台中心部の並木道を探します。街路の幅と、街区に点在する緑地の配置を見比べてください。','센다이 중심부의 가로수길을 찾아보세요. 도로 폭과 시가지 녹지의 분포를 비교해 보세요.','寻找仙台中心的林荫大道，比较街道宽度与街区绿地的分布。','尋找仙台中心的林蔭大道，比較街道寬度與街區綠地的分布。','มองหาถนนที่มีแนวต้นไม้ในใจกลางเซ็นได เปรียบเทียบความกว้างของถนนและการกระจายของพื้นที่สีเขียวในแต่ละย่าน'],
fukuoka:['Explore Hakata’s streets and waterways, then widen the view towards the waterfront. Compare the size of city blocks and the shape of the built-up area.','博多の街路と水路を探し、水際へ視点を広げます。街区の大きさと市街地の広がり方を比較してください。','하카타의 거리와 물길을 살펴본 뒤 해안 쪽으로 시야를 넓혀 보세요. 구역의 크기와 시가지가 펼쳐진 모습을 비교해 보세요.','探索博多的街道和水道，再将视野扩大至海滨。比较街区大小和城市建成区的形状。','探索博多的街道與水道，再將視野擴大至海濱。比較街區大小與市區的形狀。','สำรวจถนนและทางน้ำในฮากาตะ แล้วขยายมุมมองไปยังริมน้ำ เปรียบเทียบขนาดของแต่ละย่านและรูปร่างของพื้นที่เมือง'],
shuri:['Compare the hilltop grounds of Shuri Castle with Naha’s surrounding streets. The selected 1970s imagery predates the 1992 reconstruction; check the official park website for current restoration and access information.','首里城の丘上の敷地と那覇の周辺街路を比較します。選択された1970年代の写真は1992年の復元より前のものです。現在の復元・公開状況は公園の公式サイトで確認してください。','슈리성의 언덕 위 부지와 나하의 주변 거리를 비교해 보세요. 선택된 1970년대 사진은 1992년 복원 이전 자료입니다. 현재 복원 및 관람 정보는 공원 공식 사이트에서 확인하세요.','比较首里城山顶用地与那霸周边街道。所选1970年代影像早于1992年的复原工程；目前修复与开放情况请查阅公园官网。','比較首里城山頂用地與那霸周邊街道。所選1970年代影像早於1992年的復原工程；目前修復與開放情況請查閱公園官網。','เปรียบเทียบพื้นที่ปราสาทชูริบนเนินเขากับถนนรอบ ๆ ในนาฮะ ภาพทศวรรษ 1970 อยู่ก่อนการบูรณะปี 1992 ตรวจสอบข้อมูลการบูรณะและการเข้าชมปัจจุบันจากเว็บไซต์ทางการของสวน']
};
const labels={
en:{name:'English',route:'',title:'Historic aerial photos & walking map',open:'Compare on the map',look:'What to look for',how:'Before you explore',help:'Open the map, choose an available photograph period and move the comparison slider. Follow the same river, road or temple grounds in both views. You can save places in this browser without an account.',coverage:'The label is the imagery series date range, not the exact date of every photograph. Coverage varies by location and zoom. The latest aerial layer is not a live view.',none:'No historical comparison layer has been selected for this location. Explore the current map and the source material instead.',near:'Explore another place',distance:'Straight-line distance; not a walking route',source:'Sources and imagery',home:'All places',markets:'Plan from your country or region',period:'Historical imagery series',now:'Latest available imagery',maplang:'The map opens in English.',about:'About this site',more:'Read the place guide',fallback:'If imagery does not load, the text and map link remain available.'},
ja:{name:'日本語',route:'ja',title:'昔の航空写真と街歩きマップ',open:'地図で昔と今を比較',look:'見比べるポイント',how:'探索のしかた',help:'地図を開いて利用できる写真の年代を選び、比較スライダーを動かします。同じ川・道路・境内を目印に見比べてください。気になった地点は登録なしでこのブラウザに保存できます。',coverage:'年代は写真シリーズの収録期間であり、すべての写真の正確な撮影日ではありません。収録範囲は場所や拡大率で異なります。最新の航空写真もライブ映像ではありません。',none:'この地点には比較用の歴史写真を指定していません。現在の地図と出典資料で周辺を探索できます。',near:'ほかの場所も見る',distance:'直線距離です。徒歩経路ではありません',source:'出典と画像',home:'地点一覧',markets:'国・地域別の旅行ガイド',period:'歴史写真の収録期間',now:'最新の収録画像',maplang:'地図は日本語で開きます。',about:'このサイトについて',more:'この場所の解説を読む',fallback:'画像が読み込めない場合も、解説と地図へのリンクは利用できます。'},
ko:{name:'한국어',route:'ko',title:'옛 항공사진과 일본 산책 지도',open:'지도에서 과거와 현재 비교',look:'비교할 포인트',how:'둘러보는 방법',help:'지도를 열고 이용 가능한 촬영 시기를 선택한 뒤 비교 슬라이더를 움직이세요. 같은 강, 도로, 사찰 부지를 기준으로 살펴보세요. 회원가입 없이 이 브라우저에 장소를 저장할 수 있습니다.',coverage:'연도는 사진 시리즈의 촬영 기간이며 모든 사진의 정확한 촬영일을 뜻하지 않습니다. 범위는 장소와 확대 수준에 따라 다릅니다. 최신 항공사진도 실시간 영상은 아닙니다.',none:'이 장소에는 비교용 옛 사진이 지정되어 있지 않습니다. 현재 지도와 출처 자료로 주변을 살펴보세요.',near:'다른 장소 둘러보기',distance:'직선거리이며 도보 경로가 아닙니다',source:'출처와 이미지',home:'장소 목록',markets:'국가·지역별 여행 안내',period:'옛 사진 촬영 기간',now:'이용 가능한 최신 사진',maplang:'지도는 한국어로 열립니다.',about:'이 사이트에 대하여',more:'장소 안내 읽기',fallback:'이미지가 로드되지 않아도 설명과 지도 링크를 이용할 수 있습니다.'},
'zh-Hans':{name:'简体中文',route:'zh-cn',title:'历史航拍照片与日本城市漫步地图',open:'在地图上比较过去与现在',look:'观察重点',how:'如何探索',help:'打开地图，选择可用的航拍年代，再移动比较滑块。以同一条河流、道路或寺院用地为参照。无需注册，即可将地点保存在此浏览器中。',coverage:'年代表示照片系列的收录时期，并非每张照片的准确拍摄日期。覆盖范围因地点和缩放级别而异。最新航拍也不是实时影像。',none:'此地点未指定历史对比图层。可通过当前地图和来源资料探索周围。',near:'探索其他地点',distance:'直线距离，不是步行路线',source:'资料与影像来源',home:'地点列表',markets:'按国家与地区查看旅行指南',period:'历史影像收录时期',now:'最新可用影像',maplang:'地图以简体中文打开。',about:'关于本站',more:'阅读地点指南',fallback:'影像无法加载时，文字介绍和地图链接仍可使用。'},
'zh-Hant':{name:'繁體中文',route:'zh-tw',title:'歷史航拍照片與日本散步地圖',open:'在地圖上比較過去與現在',look:'觀察重點',how:'如何探索',help:'開啟地圖，選擇可用的航拍年代，再移動比較滑桿。以同一條河流、道路或寺院用地為參照。無需註冊，即可將地點儲存在此瀏覽器中。',coverage:'年代表示照片系列的收錄時期，並非每張照片的準確拍攝日期。涵蓋範圍因地點與縮放層級而異。最新航拍也不是即時影像。',none:'此地點未指定歷史比較圖層。可透過目前地圖與來源資料探索周圍。',near:'探索其他地點',distance:'直線距離，不是步行路線',source:'資料與影像來源',home:'地點列表',markets:'按國家與地區查看旅遊指南',period:'歷史影像收錄時期',now:'最新可用影像',maplang:'地圖以繁體中文開啟。',about:'關於本站',more:'閱讀地點指南',fallback:'影像無法載入時，文字介紹與地圖連結仍可使用。'},
th:{name:'ไทย',route:'th',title:'ภาพถ่ายทางอากาศเก่าและแผนที่เดินเที่ยวญี่ปุ่น',open:'เปรียบเทียบบนแผนที่',look:'จุดที่น่าสังเกต',how:'วิธีสำรวจ',help:'เปิดแผนที่ เลือกช่วงเวลาของภาพที่มี แล้วเลื่อนตัวเปรียบเทียบ ใช้แม่น้ำ ถนน หรือพื้นที่วัดเดียวกันเป็นจุดอ้างอิง บันทึกสถานที่ในเบราว์เซอร์นี้ได้โดยไม่ต้องสมัครสมาชิก',coverage:'ปีที่ระบุเป็นช่วงเวลาของชุดภาพ ไม่ใช่วันที่ถ่ายที่แน่นอนของทุกภาพ พื้นที่ครอบคลุมต่างกันตามสถานที่และระดับการซูม ภาพล่าสุดไม่ใช่ภาพสด',none:'สถานที่นี้ยังไม่ได้กำหนดชั้นภาพเก่าสำหรับเปรียบเทียบ คุณสำรวจได้จากแผนที่ปัจจุบันและแหล่งข้อมูล',near:'สำรวจสถานที่อื่น',distance:'ระยะทางเส้นตรง ไม่ใช่เส้นทางเดิน',source:'แหล่งข้อมูลและภาพ',home:'รายชื่อสถานที่',markets:'คู่มือตามประเทศและภูมิภาค',period:'ช่วงเวลาของชุดภาพเก่า',now:'ภาพล่าสุดที่มี',maplang:'บทความเป็นภาษาไทย แผนที่แบบโต้ตอบเปิดเป็นภาษาอังกฤษ',about:'เกี่ยวกับเว็บไซต์',more:'อ่านคู่มือสถานที่',fallback:'หากภาพไม่โหลด ยังอ่านคำอธิบายและเปิดลิงก์แผนที่ได้'}
};
const thaiNames=['ฮิโรชิมะ','โตเกียว · อาซากุสะ','เกียวโต · คิโยมิซุ','โยโกฮามะ · มินาโตมิไร','ปราสาทโอซาก้า','คามาคุระ · พระใหญ่','โกเบ · สวนเมริเคน','ปราสาทโอคายามะ','ศิลาจารึกสึนามิอาเนโยชิ','นางาซากิ','ซัปโปโร','ฮาโกดาเตะ','ปราสาทนาโกย่า','ปราสาทฮิเมจิ','นารา · โทไดจิ','คานาซาวะ','เซ็นได','ฟุกุโอกะ · ฮากาตะ','นาฮะ · ปราสาทชูริ'];
module.exports={langs,rows,labels,thaiNames};
